M48
; DRILL file {KiCad 7.0.8} date Tue Feb 13 11:31:01 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-02-13T11:31:01-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0827
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0866
%
G90
G05
T1
X6.4283Y-3.1327
X6.4283Y-3.2327
X6.4283Y-3.3327
X6.4283Y-3.4327
X6.4283Y-3.5327
T2
X5.8969Y-3.3325
T3
X5.8969Y-3.3325
T0
M30
